auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: æž— | blog
url: http://www.linchaohui.cn
feed: /atom.xml
author_info: <a href="http://www.linchaohui.cn/">LinChaohui</a>
img_url: http://linchaohui.cn/images
